# Generated by Django 5.1.2 on 2024-11-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookevent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('event_name', models.TextField()),
                ('response', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
